### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Wh1t3Rose** [Opaque02/Plex-EpisodeNotifier#2]
Followed all your steps. Everything is good until I run the command `$update` in the discord channel. I get this from console

```
root@Ecorp-Unraid-01:/mnt/user/SW/Plex-EpisodeNotifier-main# python3 UserEpisodeNotification\ v1.0.0.py 
Connected to Plex!
starting Discord...
We have logged in as Shodan#3047
------------------------------------------------
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/lib64/python3.9/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/mnt/user/SW/Plex-EpisodeNotifier-main/UserEpisodeNotification v1.0.0.py", line 189, in on_message
    show=message.content.split("\n")[1]
IndexError: list index out of range
```

**Comment by Opaque02** [comment]
Hey! So that section there is getting the message from Tautulli and reading it out. It sounds like the way you have your Tautulli notifications are a bit different - do you mind showing me what the notification you got in the notification channel is? It should be 2 lines, and the second line should have the show name and episode in there
