### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'Settings.txt'

### ISSUE THREAD

**Issue by Valhallle** [Opaque02/Plex-EpisodeNotifier#4]
Hello,

When I try to add a show on my follow list, I got this error message:
FileNotFoundError: [Errno 2] No such file or directory: 'Settings.txt'

I tried to manually create the "settings.txt" file, even to change "settings.txt" with the full path, but always the same error. 

Full error:
 Connected to Plex!
starting Discord...
We have logged in as Show Tracker#7740
------------------------------------------------
Update complete
Ignoring exception in on_raw_reaction_add
Traceback (most recent call last):
  File "C:\Users\desou\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "E:\Bureau\Notifier\UserEpisodeNotification v1.0.0.py", line 206, in on_raw_reaction_add
    output = addShow(userID,str(show))
  File "E:\Bureau\Notifier\UserEpisodeNotification v1.0.0.py", line 55, in addShow
    userCheck(user)
  File "E:\Bureau\Notifier\UserEpisodeNotification v1.0.0.py", line 103, in userCheck
    userSettings = open("Settings.txt",mode='r')
FileNotFoundError: [Errno 2] No such file or directory: 'Settings.txt'

**Comment by chiggerz** [comment]
Needs to be Settings.txt not settings.txt
